apiVersion: batch/v1
kind: CronJob
metadata:
  name: producer
  labels:
    app: pipem.io
    component: producer
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: producer
        spec:
          restartPolicy: OnFailure
          containers:
            - name: producer
              image: {{ .Values.image }}:{{ .Values.version }}
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "10m"
                limits:
                  memory: "256Mi"
                  cpu: "100m"
              envFrom:
                - configMapRef:
                    name: pipem-config
              env:
                - name: 'MONGODB_URI'
                  valueFrom:
                    secretKeyRef:
                      name: pipem-secret
                      key: MONGODB_URI